apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: my-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pods
  template:
    metadata:
      labels:
        app: my-pods
    spec:
      containers:
      - name: image
        image: $_IMAGE


