steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  script: |
    #!/usr/bin/env bash
    run deploy my-backend --image=us-docker.pkg.dev/project/image --region=us-central1 --project=$PROJECT_ID
tags: ["cloud-build-failures"]
