steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  script: |
    #!/usr/bin/env bash
    gcloud run deploy my-backend --image=us-docker.pkg.dev/project/image --region=us-central1 --project=$_TO_TARGET_PROJECT
  automapSubstitutions: true
tags: ["cloud-build-failures"]
