steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  script: |
    #!/usr/bin/env bash
    gcloud run deploy my-backend --image=us-docker.pkg.dev/cloudrun/container/hello --region us-central1
tags: ["cloud-build-failures"]
